### ISSUE TITLE
Some items were not found in users inventory

### ISSUE THREAD

**Issue by fortza** [pepzwee/node-csgo-web-tradebot#10]
Sometime even u just enter on site when u exchange get " Some items were not found in users inventory" or "Some items were not found in bot inventory" and u need to refresh site to fix this but every time.

**Comment by fortza** [comment]
the problem of this bug is [session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/1231231eqwdssfsdfgdgqafadfqwr.json'

**Comment by fortza** [comment]
so the problem is from session

**Comment by fortza** [comment]
Error: Unknown SteamID input format "  https://steamcommunity.com/tradeoffer/new/?partner=#&token=# Create New URL If you"
    at new SteamID (/home/bot/node_modules/steamid/index.js:101:9)
    at new TradeOffer (/home/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:189:18)
    at TradeOfferManager.createOffer (/home/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:25:14)
    at Trade.validateOffer (/home/bot/index.js:159:45)
    at self.getInventory (/home/bot/lib/index.js:98:36)
    at Request.request [as _callback] (/home/bot/lib/inv.js:44:20)
    at Request.self.callback (/home/bot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/bot/node_modules/request/request.js:1081:10)

**Comment by pepzwee** [comment]
Sessions are for authentication only it shouldn't be the cause of `Some items ere not found in users inventory` error.

**Comment by pepzwee** [comment]
The last error you commented, someone gave a wrong trade link.

**Comment by fortza** [comment]
ok

**Comment by fortza** [comment]
i think because auto deleteion of session ? get this " some items are not found in users invetory " ?

**Comment by pepzwee** [comment]
No

**Comment by fortza** [comment]
How much u want in money for add Float info and stickers ?

**Comment by Dakshster** [comment]
Any fix on this?

**Comment by Dakshster** [comment]
I fixed this bug in the following pull request - 
https://github.com/pepzwee/node-csgo-web-tradebot/pull/24
