### ISSUE TITLE
Error when using 'node index.js'

### ISSUE THREAD

**Issue by itzMal** [pepzwee/node-csgo-web-tradebot#111]
1. [Operating System]: Ubuntu 14.04.5 x64
2. [Node.js version]: v6.11.3
3. [How did you start the script]: I know I was supposed to use PM2, but instead I decided to use node index.js to make sure there weren't any errors. It then ended up saying this:

/var/www/html/lib/prices.js:29
        } else (!error && response.statusCode === 200) {
                                                       ^

SyntaxError: Unexpected token {
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/lib/index.js:151:1)

Is it because I am on Ubuntu 14.04.5? I am at a loss as to what to do here. I set everything correctly up in config.js. Thank you!

**Comment by itzMal** [comment]
Nevermind, I fixed it!

**Comment by FreddyFish** [comment]
No, no, no.. Dont that that :P 
What was the issue? Share it with the community, if someone in the future gets the same problem you, i'm sure they would appreciate if you wrote the solution here.

**Comment by pepzwee** [comment]
He's either using some old files or has changed the ``prices.js`` file. Line 29 has no ``else`` statement like that in the current repo.

**Comment by FreddyFish** [comment]
Ahhh i see. :P
