### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by csjunkiedotcom** [pepzwee/node-csgo-web-tradebot#160]
Bot (bot_1) has been logged-in.
[!] Website server is online.
[!] Socket server is online.
[!] Prices are updated.
[!] All bots online.
[FloatChecker:Error] Could not get inventory for "bot_1", can't set floats.
/var/www/html/node_modules/async/dist/async.js:966
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /var/www/html/node_modules/async/dist/async.js:966:32
    at startFloatChecker (/var/www/html/lib/bots.js:97:28)
    at Trade.getInventory (/var/www/html/lib/bots.js:152:20)
    at Request.request [as _callback] (/var/www/html/lib/inv.js:64:16)
    at Request.self.callback (/var/www/html/node_modules/request/request.js:185:                                                                                                                                                             22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/html/node_modules/request/request.js:1161:1                                                                                                                                                             0)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)

**Comment by csjunkiedotcom** [comment]
i have setup a /polls/bot_1.json
with {} as the only thing in the file.

**Comment by iDefineHD** [comment]
This project is no longer maintained or supported by the original creator, that being said, to me it looks as if you may have a bot that has a private inventory, hence its returning the callback/trace.

**Comment by iDefineHD** [comment]
As this is an old topic, and hasn't had any activity, I will now close.
