### ISSUE TITLE
ERR: CALLBACK

### ISSUE THREAD

**Issue by Suchismit4** [pepzwee/node-csgo-web-tradebot#163]
C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\node_modules\async\dist\async.js:322
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\node_modules\async\dist\async.js:322:36
    at startFloatChecker (C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\lib\bots.js:99:57)
    at async.eachOfSeries (C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\lib\bots.js:172:20)
    at wrapper (C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\node_modules\async\dist\async.js:272:20)
    at replenish (C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\node_modules\async\dist\async.js:439:29)
    at C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\node_modules\async\dist\async.js:449:13
    at eachOfLimit$1 (C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\node_modules\async\dist\async.js:475:34)
    at awaitable(eachOfLimit$1) (C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\node_modules\async\dist\async.js:208:32)
    at Object.eachOfSeries (C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\node_modules\async\dist\async.js:662:16)
    at Object.awaitable(eachOfSeries) (C:\Users\HP\Desktop\node-csgo-web-tradebot-master\node-csgo-web-tradebot-master\node_modules\async\dist\async.js:208:32)

**Comment by Suchismit4** [comment]
Request a review & possible fix.

**Comment by iDefineHD** [comment]
I am unable to recreate this error at the moment, what version of node are you running?

**Comment by pepzwee** [comment]
Possibly related to float checking, does the account have CS:GO in the library

**Comment by Suchismit4** [comment]
I am using, node v10.16.3 and yes the account has CSGO in the lib.

**Comment by Suchismit4** [comment]
After this was redone ( i believe) by iDefineHD, the thing broke.. it doesn't even load now... 
1. it starts and then throws this error.
2. The website gets online for like 4s and then breaks
Oh! also

`
Failed to create folder/file, please add manually.
[!] All bots online.
[FloatChecker:Progress] Starting to acquire floats for bot "bot_1". This can take a while if you have a lot of items.
[FloatChecker:Progress] Done floats for bot "bot_1".
`

What failed "folder/file"?

**Comment by iDefineHD** [comment]
Hi, that error is generic, will sort that out. The folder is polls folder. which would contain bot_1.json

**Comment by iDefineHD** [comment]
Pusing some more code, from further tests, I gathered this was from not having the polls folder with its json file, I have now changed to code to make a directory and then write the file, something that wasnt in the original, but now is. Going to push it now, all my tests have passed, and all seems to be functioning.

**Comment by iDefineHD** [comment]
Please use the last commit. Something funcky was going on and not commiting properly.
Latest should sort it.

**Comment by Suchismit4** [comment]
Okay! I will have a look. I will get back to you if there's any more problem. Closing this for now.

**Comment by iDefineHD** [comment]
> 
> 
> Okay! I will have a look. I will get back to you if there's any more problem. Closing this for now.

Sure, np. Let me know. Other than that, I can't seem any other fix, as it was reproduced and fixed with the above.
