### ISSUE TITLE
Site wont work

### ISSUE THREAD

**Issue by noodiot** [pepzwee/node-csgo-web-tradebot#174]
### Expected behavior
After running "node index.js" i get this error and the site doesn't start. The website and socket server start but then this happens and the site doesn't work. `Bot (bot_1) has been logged-in.
[!] Website server is online.
[!] Socket server is online.
/EzyTrades/index.js:17
const Trade = new TradeBot({ io })
              ^

TypeError: TradeBot is not a constructor
    at Object.<anonymous> (/EzyTrades/index.js:17:15)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.j:71:12)
    at internal/main/run_main_module.js:17:47
root@ezytrades:/EzyTrades#
`
### Actual behavior
neither will show the inventory, both just have "Something went wrong.. please try again! (401)" in a  red box
### Steps to reproduce the behavior
I don't know how to reproduce this. I bought an API and everything is in the config as it should be
### Other
1. [Operating System]: Ubuntu 16.04.6
2. [Node.js version]: 13
3. [How did you start the script]: node index.js

**Comment by iDefineHD** [comment]
Hi, me and pepz dont officially support the project anymore, but with that being said. What version of node is being used?
