### ISSUE TITLE
(node:8492) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by r00t3r5** [pepzwee/node-csgo-web-tradebot#23]
[Operating System]: Windows 10
[Node.js version]: v7.5.0

start server with node index.js and add steam guard code after this i get this error :)
```
(node:10508) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
fs.js:90
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open 'C:\nodeprojects\polls\bot_1.json'
```

**Comment by FreddyFish** [comment]
Create a file in /polls/ named bot_1.json
And write [ ] into it.

**Comment by r00t3r5** [comment]
Not working just give me error 
`(node:11528) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
                       (node:11528) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

**Comment by pepzwee** [comment]
That error doesn't help. I'm going to need a full error stack to fix anything.

**Comment by Dakshster** [comment]
Hi,

This error occurs due to two reasons - 

1.  @FreddyFish Mentioned above.
2. You've node.js v7.5.0 Version on Windows.

Please Install the LTS Version of Node.js as most modules used in this project are based over that.

**Comment by pepzwee** [comment]
Closing due to inactivity by the original author.

**Comment by jhilgenberg** [comment]
I have the same problem on my debian 8 x64, i'm using node v6.10.2 LTS and receive this error:

`/node-csgo-web-tradebot/node_modules/async/dist/async.js:941
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /root/node-csgo-web-tradebot/node_modules/async/dist/async.js:941:32
    at self.instances.(anonymous function).manager.setCookies (/root/node-csgo-web-tradebot/lib/bots.js:53:28)
    at checkDone (/root/node-csgo-web-tradebot/node_modules/steam-tradeoffer-manager/lib/index.js:98:4)
    at _community.getWebApiKey (/root/node-csgo-web-tradebot/node_modules/steam-tradeoffer-manager/lib/index.js:144:4)
    at SteamCommunity.<anonymous> (/root/node-csgo-web-tradebot/node_modules/steamcommunity/components/webapi.js:15:11)
    at Request._callback (/root/node-csgo-web-tradebot/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/root/node-csgo-web-tradebot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/node-csgo-web-tradebot/node_modules/request/request.js:1171:10)
`

**Comment by pepzwee** [comment]
@jhilgenberg There was an error with setting your cookies, but it shouldn't call ``callback`` twice. I'll look into it.

**Comment by jhilgenberg** [comment]
@pepzwee just an additional information. The script logs in successfully and also changes the Name of the bot, but after that it crashes. 

Is it correct that the twoFactorCode is empty in the config.js? I've filled everything except this one.

**Comment by pepzwee** [comment]
That's incorrect. It should have your ``shared_secret`` code.

**Comment by jhilgenberg** [comment]
@pepzwee okay, i've added the shared_secret but i still receive the same error. Maybe i have something more wrong. 

This is how i filled the config.js:
accountName = Steam Account Name
password = Steam Account Password
twoFactorCode = shared_secret out of the .maFile
identitySecret = identitySecret out of the .maFile
steamID64 = steamID64 of the Bot
personaName = Bot Nickname

```javascript
~/node-csgo-web-tradebot# node index.js
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
[!] Prices are updated.
/root/node-csgo-web-tradebot/node_modules/async/dist/async.js:941
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /root/node-csgo-web-tradebot/node_modules/async/dist/async.js:941:32
    at self.instances.(anonymous function).manager.setCookies (/root/node-csgo-web-tradebot/lib/bots.js:53:28)
    at checkDone (/root/node-csgo-web-tradebot/node_modules/steam-tradeoffer-manager/lib/index.js:98:4)
    at _community.getWebApiKey (/root/node-csgo-web-tradebot/node_modules/steam-tradeoffer-manager/lib/index.js:144:4)
    at SteamCommunity.<anonymous> (/root/node-csgo-web-tradebot/node_modules/steamcommunity/components/webapi.js:15:11)
    at Request._callback (/root/node-csgo-web-tradebot/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/root/node-csgo-web-tradebot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/root/node-csgo-web-tradebot/node_modules/request/request.js:1171:10)
```

**Comment by pepzwee** [comment]
@jhilgenberg Replace ``lib/bots.js`` with this one https://gist.github.com/pepzwee/486b3e8f989979ba652f9fa5697a2b4b

Run the script again after you've replaced it and tell me the error.

**Comment by jhilgenberg** [comment]
@pepzwee first i wanted to thank you for your effort! You reply so fast, awesome! Here is the output:

```javascript
~/node-csgo-web-tradebot# node index.js
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
[!] Prices are updated.
webSession setCookies Error Error: Access Denied
    at SteamCommunity.<anonymous> (/root/node-csgo-web-tradebot/node_modules/steamcommunity/components/webapi.js:15:20)
    at Request._callback (/root/node-csgo-web-tradebot/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/root/node-csgo-web-tradebot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/root/node-csgo-web-tradebot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Gunzip.<anonymous> (/root/node-csgo-web-tradebot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
/root/node-csgo-web-tradebot/node_modules/async/dist/async.js:941
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /root/node-csgo-web-tradebot/node_modules/async/dist/async.js:941:32
    at /root/node-csgo-web-tradebot/lib/bots.js:52:28
    at checkDone (/root/node-csgo-web-tradebot/node_modules/steam-tradeoffer-manager/lib/index.js:98:4)
    at _community.getWebApiKey (/root/node-csgo-web-tradebot/node_modules/steam-tradeoffer-manager/lib/index.js:144:4)
    at SteamCommunity.<anonymous> (/root/node-csgo-web-tradebot/node_modules/steamcommunity/components/webapi.js:15:11)
    at Request._callback (/root/node-csgo-web-tradebot/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/root/node-csgo-web-tradebot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/root/node-csgo-web-tradebot/node_modules/request/request.js:1171:10)
```

**Comment by pepzwee** [comment]
That error means that your account is limited.
Source: https://dev.doctormckay.com/topic/199-error-access-denied-with-a-full-steam-account/

Have you added 5 ($/€) to your Steam account?
1. **If yes**, login to your account and go to the market page, it should show you how long your account is limited for.
2. **If no**, login to your account and add funds. Go to the market page, to see how long your account is limited for.

**Comment by jhilgenberg** [comment]
@pepzwee works like a charm! Thank you!
