### ISSUE TITLE
Unknown SteamID input format

### ISSUE THREAD

**Issue by fortza** [pepzwee/node-csgo-web-tradebot#25]
```
Error: Unknown SteamID input format " https://steamcommunity.com/tradeoffer/new/?partner=183172126&token=K9_o2T9x Create a new url"
    at new SteamID (/home/bot/node_modules/steamid/index.js:101:9)
    at new TradeOffer (/home/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:189:18)
    at TradeOfferManager.createOffer (/home/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:25:14)
    at Trade.validateOffer (/home/bot/index.js:187:45)
    at self.getInventory (/home/bot/lib/index.js:152:36)
    at Request.request [as _callback] (/home/bot/lib/inv.js:49:20)
    at Request.self.callback (/home/bot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/bot/node_modules/request/request.js:1081:10)
```

when u get this error automatical site crash and restart

**Comment by pepzwee** [comment]
It's because that's an invalid trade link.
