### ISSUE TITLE
Error when running index.js

### ISSUE THREAD

**Issue by Kevje4** [pepzwee/node-csgo-web-tradebot#42]
### Expected behavior
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
### Actual behavior
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at Object.<anonymous> (/var/www/html/index.js:20:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

### Other
1. [Operating System]: Ubuntu 14.04
2. [Node.js version]: Node 7.0
3. [How did you start the script]: node index.js

### Error Stack

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at Object.<anonymous> (/var/www/html/index.js:20:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by FreddyFish** [comment]
Is port 80 already in use?
Do you have XAMPP, Apache or any other apps running that are using port 80?
- This could also be because skype is running, (I belive, skype is using port 80 as well)
Try to change the port number in the config file.

**Comment by Kevje4** [comment]
I am running it on a online host

**Comment by FreddyFish** [comment]
Is the port 80 in use?

**Comment by Kevje4** [comment]
How do i check that?

**Comment by FreddyFish** [comment]
You should probably know if something is using port 80.
What happends when you visit the IP adress of the server?

**Comment by Kevje4** [comment]
I get to the normal website and everything looks normal but i cant sign in or load inventories

**Comment by Kevje4** [comment]
I have apache on the server, does that make a diffrence?

**Comment by FreddyFish** [comment]
Yes it does. Apache is using port 80, that's what i told you in my first comment.

**Comment by Kevje4** [comment]
I changed the port to 81 in the config now and i get this error:


Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
[!] Prices are updated.
(node:25301) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
fs.js:92
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open './polls/bot_1.json'

**Comment by FreddyFish** [comment]
#34

**Comment by Kevje4** [comment]
Did that and now i get this errror:
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
[!] Prices are updated.
(node:25434) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

and still cant sign in
