### ISSUE TITLE
Port error...

### ISSUE THREAD

**Issue by LEIDERPRO** [pepzwee/node-csgo-web-tradebot#44]
### Other
1. [Operating System]: <Debian 8>
2. [Node.js version]: <v7.10.0>
3. [How did you start the script]: <node index.js>

### Error Stack

root@leiderpro:/var/www/html# node index.js
Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at Object.<anonymous> (/var/www/html/index.js:20:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
root@leiderpro:/var/www/html#

**Comment by LEIDERPRO** [comment]
node v7.10.0

**Comment by FreddyFish** [comment]
Port 80 is already in use.
Is apache running?

**Comment by LEIDERPRO** [comment]
yes apache running

**Comment by FreddyFish** [comment]
Yeah, that's why.
Apache is using port 80. 

What you can do:
Stop the service by running : sudo service apache2 stop
Delete apache2 by running: sudo apt-get remove apache2

**Comment by LEIDERPRO** [comment]
can i no use both?

**Comment by FreddyFish** [comment]
Yes you can.
You can change the port in the config.js

Remember when changing the port it also changes the URL a bit. ex: csg0.trade:>port< / csg0.trade:81

**Comment by LEIDERPRO** [comment]
oh nice man thanks :D
