### ISSUE TITLE
Error: listen EADDRINUSE :::80

### ISSUE THREAD

**Issue by SchlachtSahne** [pepzwee/node-csgo-web-tradebot#47]
Hey, can any one help me please?

Bot (bot_1) has been logged-in.
[!] All bots online.
[!] Website server is online.
[!] Socket server is online.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Object.<anonymous> (/var/www/html/index.js:20:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by SchlachtSahne** [comment]
In the config file from Nodejs?

**Comment by iDefineHD** [comment]
The config.js file is one of the files you downloaded. Along with the index.js and such

**Comment by SchlachtSahne** [comment]
Okey works but then I get 

(node:1219) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
fs.js:113
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open './polls/bot_1.json'

**Comment by iDefineHD** [comment]
Again. Create the folder. It will then populate.

**Comment by SchlachtSahne** [comment]
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at async.eachOfSeries (/var/www/html/lib/bots.js:44:56)
    at replenish (/var/www/html/node_modules/async/dist/async.js:946:17)
    at /var/www/html/node_modules/async/dist/async.js:950:9
    at eachOfLimit (/var/www/html/node_modules/async/dist/async.js:975:24)
    at Object.<anonymous> (/var/www/html/node_modules/async/dist/async.js:980:16                                                                             )
    at Trade.startBots (/var/www/html/lib/bots.js:17:11)
    at new Trade (/var/www/html/lib/index.js:21:10)
    at Object.<anonymous> (/var/www/html/index.js:17:15)
    at Module._compile (module.js:569:30)

**Comment by SchlachtSahne** [comment]
Is it enough to start index.js ?

**Comment by FreddyFish** [comment]
Read previous issues.
